tunnel: wuchang-core-tunnel
credentials-file: C:\Users\User\.cloudflared\wuchang-core-tunnel.json

ingress:
  - hostname: wuchang.life
    service: http://localhost:8069
  - hostname: preview.wuchang.life
    service: http://localhost:8000
  - service: http_status:404
